Bertoni_test/Models/Albums.cs
using Bertoni_test.Controllers.Tools;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Newtonsoft.Json;
using System.Web.Script.Serialization;

namespace Bertoni_test.Models
{
    public class Albums
    {
        public int userId { get; set; }
        public int id { get; set; }
        public string title { get; set; }

        public static async Task<List<Albums>> parseFromJSON()
        {
            var data = await JsonRequests.request("albums"); 
            var json_serializer = new JavaScriptSerializer();
            var routes_list = json_serializer.Deserialize<List<Albums>>(data);
            return routes_list;
        }
    }
}

Bertoni_test/Models/Comments.cs
using Bertoni_test.Controllers.Tools;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Script.Serialization;

namespace Bertoni_test.Models
{
    public class Comments
    {
        public int postId { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string body { get; set; }

        public static async Task<List<Comments>> parseFromJSON(int? photoId)
        {
            var data = await JsonRequests.request("comments");
            var json_serializer = new JavaScriptSerializer();
            var routes_list = json_serializer.Deserialize<List<Comments>>(data);
            return routes_list.Where(c=>c.postId == photoId).ToList();
        }
    }
}

Bertoni_test/Models/Photos.cs
using Bertoni_test.Controllers.Tools;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Script.Serialization;

namespace Bertoni_test.Models
{
    public class Photos
    {
        public int albumId { get; set; }
        public int id { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public string thumbnailUrl { get; set; }

        public static async Task<List<Photos>> parseFromJSON(int? albumId)
        {
            var data = await JsonRequests.request("photos");
            var json_serializer = new JavaScriptSerializer();
            var routes_list = json_serializer.Deserialize<List<Photos>>(data);
            return routes_list.Where(a => a.albumId == albumId).ToList();
        }
    }
}

Bertoni_test/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Bertoni_test.Models;

namespace Bertoni_test.Controllers
{
    public class AlbumsController : Controller
    {
        // GET: Albums
        public async Task<ActionResult> Index()
        {
            List<Albums> albums = await Albums.parseFromJSON();
            return View(albums);
        }
    }
}

Bertoni_test/Controllers/CommentsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using Bertoni_test.Models;

namespace Bertoni_test.Controllers
{
    public class CommentsController : Controller
    {
        // GET: Comments
        public async Task<ActionResult> Index(int? id)
        {
            List<Comments> comments = await Comments.parseFromJSON(id);
            return View(comments);
        }
    }
}

Bertoni_test/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Bertoni_test.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("Index", "albums");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Bertoni_test/Controllers/PhotosController.cs
using Bertoni_test.Models;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Bertoni_test.Controllers
{
    public class PhotosController : Controller
    {
        // GET: Photos
        public async Task<ActionResult> Index(int? id)
        {
            var photos = await Photos.parseFromJSON(id);
            return View(photos);
        }

    }
}

Bertoni_test/Views/Albums/Index.cshtml
@model IEnumerable<Bertoni_test.Models.Albums>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Albums</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.ActionLink("View Photos", "Index", "Photos", new { id = item.id }, new { @class = "navbar-brand" })

        </td>
    </tr>
}

</table>

Bertoni_test/Views/Comments/Index.cshtml
@model IEnumerable<Bertoni_test.Models.Comments>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Comments</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.postId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.body)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.postId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.body)
        </td>
    </tr>
}

</table>

Bertoni_test/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Bertoni_test/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Bertoni_test/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Bertoni_test/Views/Photos/Index.cshtml
@model IEnumerable<Bertoni_test.Models.Photos>

@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Photos</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.albumId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.thumbnailUrl)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.albumId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
			<img src="@Html.DisplayFor(modelItem => item.thumbnailUrl)" alt="Alternate Text" /> 
        </td>
        <td>
            <button class="btn-block success load-comments">View Comments</button>
            @Html.ActionLink("View Comments", "Index", "Comments", new { id = item.id }, new { @class = "navbar-brand" })
        </td>
    </tr>
}

</table>

<script>
	$(".load-comment").click(function (e) {
		alert("asdasd");
	});
</script>

Bertoni_test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="https://code.jquery.com/jquery-3.5.1.slim.js"
            integrity="sha256-DrT5NfxfbHvMHux31Lkhxg42LY6of8TaYyK50jnxRnM="
            crossorigin="anonymous"></script>

</body>
</html>